# Generated by Django 6.0.6 on 2026-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, help_text='PokeAPI-Pfad ohne Basis-URL, z.B. "pokemon/25".', max_length=255, unique=True)),
                ('payload', models.JSONField(help_text='Die unveraenderte JSON-Antwort der PokeAPI.')),
                ('fetched_at', models.DateTimeField(auto_now=True, help_text='Wann der Eintrag zuletzt von der PokeAPI geholt wurde.')),
            ],
            options={
                'verbose_name': 'Gecachte PokeAPI-Ressource',
                'verbose_name_plural': 'Gecachte PokeAPI-Ressourcen',
                'ordering': ['path'],
            },
        ),
    ]
