# Generated by Django 6.0.6 on 2026-07-13 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Platz im Team (0 bis 5).')),
                ('pokemon_id', models.PositiveIntegerField(help_text='Nummer des Pokemon, z.B. 25.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team-Mitglied',
                'verbose_name_plural': 'Team-Mitglieder',
                'ordering': ['user', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slot'), name='einmaliger_platz')],
            },
        ),
    ]
