# Generated by Django 6.0.6 on 2026-07-13 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teammember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField(help_text='Nummer des Pokemon, z.B. 25.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorit',
                'verbose_name_plural': 'Favoriten',
                'ordering': ['user', 'pokemon_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pokemon_id'), name='einmaliger_favorit')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField(help_text='Nummer des Pokemon, z.B. 25.')),
                ('text', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['user', 'pokemon_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pokemon_id'), name='einmalige_notiz')],
            },
        ),
    ]
