# Generated by Django 6.0.6 on 2026-07-13 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fought_at', models.DateTimeField(help_text='Wann der Kampf stattfand.')),
                ('result', models.CharField(choices=[('win', 'Sieg'), ('loss', 'Niederlage')], max_length=8)),
                ('total_damage_dealt', models.PositiveIntegerField(default=0)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('pokemon_used', models.PositiveSmallIntegerField(default=0)),
                ('gym_leader_name', models.CharField(blank=True, max_length=60)),
                ('gym_leader_type', models.CharField(blank=True, max_length=20)),
                ('mvp_name', models.CharField(blank=True, max_length=60)),
                ('mvp_pokemon_id', models.PositiveIntegerField(blank=True, null=True)),
                ('mvp_damage', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kampf',
                'verbose_name_plural': 'Kaempfe',
                'ordering': ['-fought_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=60)),
                ('types', models.JSONField(default=list, help_text='Die Typen, z.B. ["fire"].')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.battlerecord')),
            ],
            options={
                'verbose_name': 'Kampf-Teilnehmer',
                'verbose_name_plural': 'Kampf-Teilnehmer',
                'ordering': ['id'],
            },
        ),
    ]
