# Generated by Django 6.0.6 on 2026-07-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_battlerecord_battleparticipant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team-Preset',
                'verbose_name_plural': 'Team-Presets',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamPresetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField()),
                ('pokemon_id', models.PositiveIntegerField()),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.teampreset')),
            ],
            options={
                'verbose_name': 'Preset-Mitglied',
                'verbose_name_plural': 'Preset-Mitglieder',
                'ordering': ['slot'],
            },
        ),
    ]
