# Generated by Django 6.0.6 on 2026-07-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teampreset_teampresetmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('german', models.CharField(db_index=True, max_length=60)),
                ('english', models.CharField(db_index=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Pokemon-Name',
                'verbose_name_plural': 'Pokemon-Namen',
                'ordering': ['pokemon_id'],
            },
        ),
    ]
