# Generated by Django 6.0.6 on 2026-07-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pokemonname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_key', models.CharField(help_text='Schluessel des Arenaleiters, z.B. "rocko".', max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arena-Orden',
                'verbose_name_plural': 'Arena-Orden',
                'ordering': ['user', 'earned_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'leader_key'), name='einmaliger_orden')],
            },
        ),
    ]
