"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Die .env liegt im Projektwurzelverzeichnis (eine Ebene ueber backend/) und
# wird mit dem Frontend geteilt. Dort stehen die KI-API-Keys.
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1n8zvz*xk0t!da0svskxe+tk4cuuk9vlhnfwh%+=pyj^_7u+tn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Drittanbieter
    'rest_framework',
    # Gibt jedem Login einen Token, den das Frontend mitschickt (M3).
    'rest_framework.authtoken',
    'drf_spectacular',
    'corsheaders',
    # Eigene Apps
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CORS so frueh wie moeglich, vor CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # SQLite erlaubt nur EINEN Schreiber gleichzeitig. Das Frontend holt
            # beim Start aber alle 18 Typen parallel - die wollen alle cachen.
            # WAL: Lesen und Schreiben blockieren sich nicht mehr gegenseitig.
            'init_command': 'PRAGMA journal_mode=WAL;',
            # Ein wartender Schreiber gibt nicht sofort auf, sondern 20 Sekunden.
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework: drf-spectacular als Schema-Generator nutzen.
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Wer bin ich? Das Frontend schickt "Authorization: Token <key>" mit; daran
    # erkennt DRF den Nutzer und setzt request.user.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Bremse fuer den KI-Proxy (siehe api/throttling.py). Ohne sie koennte eine
    # einzige Seite das Guthaben des API-Keys leerlaufen lassen.
    'DEFAULT_THROTTLE_RATES': {
        'ai': '30/min',
    },
}

# Swagger / OpenAPI (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Pokedex Backend API',
    'DESCRIPTION': 'Backend fuer den Pokedex (Caching, Accounts, Team-Daten).',
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS: erlaubt dem lokalen Frontend, das Backend aufzurufen.
CORS_ALLOWED_ORIGINS = [
    # server.js (npm start)
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    # VS Code Live Server
    'http://localhost:5500',
    'http://127.0.0.1:5500',
]

# PokeAPI-Cache: So viele Tage gilt eine gespeicherte Antwort als frisch.
# Pokemon-Daten aendern sich praktisch nie, darum ist eine Woche grosszuegig.
POKEAPI_CACHE_TTL_DAYS = 7
